#!/usr/bin/env bash

# Script name
sn=$(basename "$0")
if [[ "$#" -eq 0 ]]; then
    echo "Usage: $sn your.awesome.bigWig" 1>&2
    echo "       $sn your.awesome.bigBed" 1>&2
    echo "       $sn your.awesome.Watson.bigWig \"[hide,dense,full,pack,squish]\"" 1>&2
    echo "Do not use *.Crick.bigWig" 1>&2
    exit 1
fi

url_root=zlab-trackhub.umassmed.edu
p=$1
vis="${2}"
if [[ -z "$vis" ]]; then
    vis=2
fi
p=$(readlink -e $p)
rel=${p#/nfs/www@bib7/zlab-trackhub/}
rel=$(dirname ${rel})
# echo ${rel}
fn=$(basename ${p})
suf=${fn##*.}
if [[ $suf == "bigwig" || $suf == "bigWig" ]]; then
    type=bigWig
elif [[ $suf == "bigbed" || $suf == "bigBed" ]]; then
    type=bigBed
else
    echo "Unknown file extension: $suf" 1>&2
fi
    
prefix=${i%.Watson.bigWig}

if [[ $fn =~ .*Watson.* ]]; then
    # Signals with strand
    crick=$(echo ${fn} | sed 's/Watson/Crick/')
    echo "track type=${type} name=\"${fn}\" bigDataUrl=http://${url_root}/${rel}/${fn} color=0,0,255 visibility=$vis priority=50 ${opts}"
    echo "track type=${type} name=\"${crick}\" bigDataUrl=http://${url_root}/${rel}/${crick} color=255,0,0 visibility=$vis priority=50 ${opts}"
else
    # Signals without strand
    echo "track type=${type} name=\"${fn}\" bigDataUrl=http://${url_root}/${rel}/${fn} color=0,0,255 visibility=${vis} priority=50 ${opts}"
fi
