#!/usr/bin/env python

import sys
import fileinput
import numpy as np

def avg(l):
    return sum(l) / float(len(l))

total_reads = 0
total_species = 0
# Used to calculate the average ntm and copy number
reads_ntm = {}
reads_copy = {}

for line in fileinput.input():
    line = line.strip()
    col = line.split()
    seq, copy = col
    copy = int(copy)

    total_reads += copy
    total_species += 1
    reads_copy[seq] = copy

avg_copy = avg( reads_copy.values() )
median_copy = np.median( np.array( reads_copy.values() ), axis=0)

print "number_reads" + "\t" + str(total_reads)
print "number_species" + "\t" + str(total_species)
print "average_species_copy_number" + "\t" + str(avg_copy)
print "median_species_copy_number" + "\t" + str(median_copy)
    
